### PR TITLE
[WIP] Update to 1.0.0a1

### PR DESCRIPTION
**Pull request by monaka**
**Please don't merge this. This is just for sample.**

This PR is inspired by deis/postgres#129.

I tried to upgrade the official 1.0.0a.
There is no boto3 patch in this PR. Because I run my Deis Workflow on Azure and I have little knowledge about Boto/Boto3.

I'm testing this (with patched deis/postgres image) on Azure only.
It seems this doesn't fix deis/postgres#127. But generally this works well to me.

Hope some helps for hackers who know Boto/Boto3 well.

### CODE REVIEW

**Comment by kmala** [comment]
i would say cherry pick the commits on `Commits on Feb 20, 2016` from https://github.com/deis/wal-e/commits/boto3-upgrade and from PR's https://github.com/deis/wal-e/pull/1 and https://github.com/deis/wal-e/pull/3 on top of the 1.0.0a1 release and it should be good to go.
I can help you with testing the boto3(s3) and google storage and you can do the azure testing

**Comment by monaka** [comment]
@kmala, I inspected s3 related code in the upstream. There seems have some major patches.
So it needs some more calibration tasks addition to cherry-pick....

**Comment by bacongobbler** [comment]
Indeed. Rebasing the boto3 refactor on top of wal-e 1.0.0a would not be an easy task, since upstream has refactored the underlying code in a big way.

Personally I'd rather back off boto3 as it is a (pythonic) nightmare to maintain, and I'm not the only one who thinks that. The only patch we require for deis/postgres' sake is the [hardcoded use of the s3v4 auth signature](https://github.com/deis/wal-e/blob/boto3-upgrade/wal_e/blobstore/s3/calling_format.py#L44), so if we got that [fixed in boto](https://github.com/boto/boto/issues/2623) (which, btw, has now been [PR'd](https://github.com/boto/boto/pull/3513)) then I'd be happy to move off this fork and back onto wal-e upstream.

https://github.com/boto/boto3/issues/112
https://github.com/boto/boto/issues/3306

**Comment by bacongobbler** [comment]
closing this as we plan on moving to wal-e 1.0.0 once it's available, and the PR will be at https://github.com/deis/postgres/pull/137. We will delete this repo once merged.

**Pull request closed without merging**
