### PR TITLE
fix(s3):remove the creation of unused creds object

### PR DESCRIPTION
**Pull request by kmala**

### CODE REVIEW

**Comment by kmala** [comment]
The reason for removing it now we wanted to support IAM instance profiles and this creds function has some unnecessary validations

**Comment by bacongobbler** [comment]
@kmala perhaps you should look into porting [the --aws-instance-profile flag](https://github.com/wal-e/wal-e/blob/f4f5b268327137e87737e7abd7c495f4636e7e98/wal_e/cmd.py#L193-L196) back. We should be explicit about the credentials being required unless this flag is provided, or else we could end up in a situation where we're not using IAM and AWS_ACCESS_KEY is not set in the environment. In that case wal-e should error out.

**Comment by kmala** [comment]
@bacongobbler i thought about it but then again i was like since we aren't using them anyway why should we add it unnecessarily 
wal-e will error out as boto-3 errors out if there aren't both values in the environment...Also we wouldn't be even calling the wal-e as deis/postgres itself bails out before that if the values aren't present

**Comment by mboersma** [comment]
This LGTM, but @bacongobbler is more familiar with this particular code so he should probably have the final word.

(Yes, I'm trying to resurrect mention-bot too.)

**Comment by bacongobbler** [comment]
code LGTM. creds isn't even used in the s3 calling format code, so this doesn't impact anything other than blocking boto3 from using IAM credentials. I like this change after thinking it through. :+1:

**Pull request merged**
